name: Branch Example

on:
  push:
    branches:
      - v*

jobs:
  validate:
    name: Tagging
    runs-on: ubuntu-latest

    steps:
      - name: npm install
        run: echo 'hello world'
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
